version: "3"
services:
  database:
    image: postgres:alpine
    container_name: pgfikus
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    build:
      dockerfile: Dockerfile
      context: ./database
  cache:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      # TODO: add ports to env vars
      - "6379:6379"
    volumes:
      - ./cache:/data
